name: Finney Data Genesis

concurrency:
#   group: check-rust-${{ github.ref }}
  cancel-in-progress: true

on:
  ## Allow running workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      javascriptCode:
        description: "Enter JavaScript code to execute"
        required: false
        type: "textarea"
      verbose:
        description: "Output more information when triggered manually"
        required: false
        default: ""

env:
  CARGO_TERM_COLOR: always
  VERBOSE: ${{ github.events.input.verbose }}

jobs:
  install-baedeker:
    name: install-baedeker
    runs-on: SubtensorCI
    strategy:
      matrix:
        rust-branch:
          - stable
        rust-target:
          - x86_64-unknown-linux-gnu
          # - x86_64-apple-darwin
        os:
          - ubuntu-latest
          # - macos-latest
        include:
          - os: ubuntu-latest
          # - os: macos-latest
    env:
      RELEASE_NAME: development
      # RUSTFLAGS: -A warnings
      RUSTV: ${{ matrix.rust-branch }}
      RUST_BACKTRACE: full
      RUST_BIN_DIR: target/${{ matrix.rust-target }}
      SKIP_WASM_BUILD: 1
      TARGET: ${{ matrix.rust-target }}
    steps:
      - name: Checkout Baedeker repository
        uses: actions/checkout@v3
        with:
          repository: 'UniqueNetwork/baedeker'
          path: 'baedeker'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
    
      - name: Build baedeker
        run: |
          cd baedeker
          cargo build --release
    
      - name: Prepare binary for artifact upload
        run: |
          mkdir -p ${{ github.workspace }}/bin
          cp ./baedeker/target/release/baedeker ${{ github.workspace }}/bin/
          chmod +x ${{ github.workspace }}/bin/baedeker
    
      - name: Upload baedeker binary as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: baedeker-binary
          path: ${{ github.workspace }}/bin/baedeker

  download-finney-state:
    needs: install-baedeker
    runs-on: SubtensorCI
    steps:
      - name: Download baedeker binary
        uses: actions/download-artifact@v3
        with:
          name: baedeker-binary
          path: bin

      - name: Execute baedeker
        run: |
          chmod +x bin/baedeker
          ./bin/baedeker --version
